services:
  db:
    image: postgres:15
    container_name: timeline-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: timeline
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/docker-entrypoint:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
